In [70]:
# %load no_pad.py
def categorical_crossentropy_no_pad(y_true, y_pred):
    original_pad = y_true.shape[1]
    loss = K.zeros_like(y_true[:, :, 0])
   
    y_true = y_true.reshape((-1, no_of_labels))
    y_pred = y_pred.reshape((-1, no_of_labels))
    
    indices = T.neq(y_true.sum(axis=1), 0)
    
    loss = indices * K.categorical_crossentropy(y_pred, y_true)
    loss = loss.reshape((-1, original_pad)).mean(axis=1)
    
    return loss    

def categorical_accuracy_no_pad(y_true, y_pred):
    
    y_true = y_true.reshape((-1, no_of_labels))
    y_pred = y_pred.reshape((-1, no_of_labels))
    zero_indices = T.eq(y_true.sum(axis=1), 0)
   
    aa = K.argmax(y_true, axis=1)
    bb = K.argmax(y_pred, axis=1)

    no_of_padding = zero_indices.sum()
    
    return (K.sum(K.equal(aa, bb)) - no_of_padding)/(y_true.shape[0] - no_of_padding)

In [43]:
import numpy as np
from keras import backend as K
from theano import tensor as T
no_of_labels = 2

In [100]:
y_t = np.zeros((2, 3, 2))
y_t[0, 1, 1] = 1
y_t[1, 2, 1] = 1
print(y_t)

[[[ 0.  0.]
  [ 0.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  1.]]]


In [103]:
y_r = y_t.copy()
y_r[1, 1, 1] = 1
print(y_r)
print(y_t)

[[[ 0.  0.]
  [ 0.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  1.]
  [ 0.  1.]]]
[[[ 0.  0.]
  [ 0.  1.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  1.]]]


In [104]:
print(categorical_accuracy_no_pad(y_t, y_r).eval())

0.5


In [105]:
y_t_flat = y_t.reshape((-1, no_of_labels))
print(y_t_flat)

[[ 0.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  1.]]


In [124]:
print(y_r_flat.shape[-1])
y_r_flat = y_r.reshape((-1, y_r_flat.shape[-1]))
print(y_r_flat)

2
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  1.]
 [ 0.  1.]]


In [107]:
indices = T.eq(y_t_flat.sum(axis=1), 0)
print(indices.eval())

[1 0 1 1 1 0]


In [108]:
aa = K.argmax(y_t_flat, axis=1)
print(aa.eval())

[0 1 0 0 0 1]


In [109]:
bb = K.argmax(y_r_flat, axis=1)
print(bb.eval())

[0 1 0 0 1 1]


In [110]:
print(K.equal(aa, bb).eval())

[1 1 1 1 0 1]


In [111]:
print(indices.sum().eval())

4


In [113]:
print((K.sum(K.equal(aa, bb)) - indices.sum()).eval())

1


In [114]:
print(K.sum(K.equal(aa, bb)).eval())

5


In [115]:
print(y_t_flat.shape[0])

6


In [116]:
print(categorical_accuracy_no_pad(y_t, y_r).eval())

0.5


In [119]:
zero_indices = K.equal(K.sum(y_t_flat, axis=1), 0)
print(zero_indices.eval())

[1 0 1 1 1 0]
